SELECT EXTRACT(YEAR FROM NOW());

SELECT EXTRACT(MONTH FROM NOW());

SELECT EXTRACT(DAY FROM NOW());

SELECT EXTRACT(HOUR FROM NOW());

SELECT EXTRACT(MINUTE FROM NOW());

SELECT EXTRACT(SECOND FROM NOW());

SELECT EXTRACT(WEEK FROM NOW());

SELECT EXTRACT(QUARTER FROM NOW());

SELECT EXTRACT(DOW FROM NOW());

SELECT EXTRACT(ISODOW FROM NOW());

SELECT EXTRACT(DOY FROM NOW());

SELECT EXTRACT(DECADE FROM NOW());

SELECT EXTRACT(CENTURY FROM NOW());

SELECT EXTRACT(MILLENNIUM FROM NOW());

SELECT EXTRACT(EPOCH FROM NOW());



SELECT CURRENT_DATE + 7;

SELECT CURRENT_DATE - 30;

SELECT CURRENT_DATE + INTERVAL '1 month';

SELECT CURRENT_DATE + INTERVAL '1 year';

SELECT CURRENT_DATE + INTERVAL '2 weeks';


SELECT AGE(DATE '2000-01-01');
SELECT AGE(CURRENT_DATE, '2000-01-01');

SELECT AGE('2026-06-24', '2000-01-01');